### ISSUE TITLE
[Question] Cannot run RepoList against Artifactory Docker registry configured with `Registry Paths` method

### ISSUE THREAD

**Issue by ennekein** [regclient/regclient#820] opened 2024-09-03 20:37 UTC
### Question

We are using Artifactory containing multiple Docker registries set up with the Repository Path method (https://jfrog.com/help/r/jfrog-artifactory-documentation/the-repository-path-method-for-docker).

Our registry APIs are exposed with the following equivalent URL formats:
- `https://<hostname>/v2/<docker registry name>/<...>`
- `https://<hostname>/artifactory/api/oci/<docker registry name>/v2/<...>`

We are trying to use the regclient go module to run commands against an OCI registry in Artifactory/JFrog. We are hitting an issue at the `RepoList` function, because it formats the API call as `https://<hostname>/v2/_catalog`. I see that the `repository` parameter in your API struct could be used to add the registry name between `/v2` and the command path, but it is not exposed by the `RepoList` function.

Are Artifactory Docker registries exposed with the Repository Path method something you would want to support?

### Version

```text
regclient@v0.7.1
```

### Environment
Using go module

Artifactory 7.77.11

**Comment by sudo-bmitch** [comment] 2024-09-03 21:50
Closing this as a duplicate of #792. Feel free to continue the discussion there.

**Closed** 2024-09-03 21:50 UTC
Labels: question
