### ISSUE TITLE
regsync isn't always respecting the allow/deny tags

### ISSUE THREAD

**Issue by zoredache** [regclient/regclient#576] opened 2023-10-16 21:00 UTC
### Behavior

I am sorry I don't have more specific details to reproduce my issue, it seems to happen somewhat randomly.  If someone has more details about how to troubleshoot, or get more details that would be useful.

I am using the 'allow' under 'tags' to filter out the specific things synced.  The initial sync pulls in what I want, after a while regsync pulls in a lot more tags that don't match.

    version: 1
    defaults:
      ratelimit:
        min: 60
        retry: 1h
      parallel: 2
      interval: 6h
    sync:
      - platform: linux/amd64
        source: docker.io/library/traefik
        target: registry.example.org/library/traefik
        type: repository
        tags:
          allow:
            - '2.\d+'
            - '3.\d+'
            - 'latest'

I start my image like this.

    docker container run -d --rm --net host \
      -v "$(pwd)/regsync.yml:/home/appuser/regsync.yml" \
      regclient/regsync:latest -c /home/appuser/regsync.yml server

The initial sync pulled in the tags I would have expect 2.0, 2.1, 2.10, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, latest

But at some later point a couple hours later regsync had pulled in lots of tags that didn't match my 'allow'

1.1.2, 1.1.2-alpine, 1.1-alpine, 1.2, 1.2.0, 1.2.0-alpine, ...

### Version

    docker container run -it --rm regclient/regsync:latest version

    latest version
    VCSTag:     v0.5.3
    VCSRef:     63bcd1a551acbb357d6a6aea0c50fb193aa77da9-dirty
    VCSCommit:  63bcd1a551acbb357d6a6aea0c50fb193aa77da9
    VCSState:   dirty
    VCSDate:    2023-10-06T20:40:08Z
    Platform:   linux/amd64
    GoVer:      go1.21.2
    GoCompiler: gc

    docker image inspect regclient/regsync:latest
    [
        {
            "Id": "sha256:d27ed8d96a89e4554bad2c3e32846d511906e2e8ddabd21b78f96fb070346f74",
            "RepoTags": [
                "regclient/regsync:latest"
            ],
            "RepoDigests": [
                "regclient/regsync@sha256:badf7417d2adc634e7beecbd9f85ad539e2a1e933582050e3f8436ffeea99f53"
            ],
            ...

### Environment

The local registry is running the latest stable https://hub.docker.com/_/registry software. My configuration is pretty minimal and standard.

Registry

    docker exec -it registry         /bin/registry -v
    /bin/registry github.com/docker/distribution 2.8.3

    docker image inspect registry
    [
        {
            "Id": "sha256:0ae1560ca86fd99c4932c235774a65173f550179a92e3ba101b2ef783a701d20",
            "RepoTags": [
                "registry:latest"
            ],
            "RepoDigests": [
                "registry@sha256:12a6ddd56d2de5611ff0d9735ac0ac1d1e44073c7d042477329e589c46867e4e",
                "registry@sha256:3ba2901ca93432deedc7a16d57e4d4295825132aae08aec9223808221a8baec4"
            ],
            "Parent": "",
            "Comment": "",
            "Created": "2023-10-03T04:04:10.560980382Z",

Running docker on a Debian system

    docker system info
    Client: Docker Engine - Community
     Version:    24.0.6
     Context:    default
     Debug Mode: false
     
    lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 12 (bookworm)
    Release:        12
    Codename:       bookworm

**Comment by zoredache** [comment] 2023-10-16 21:03
Sorry, I apparently didn't set my title.  I had meant to have a title like `regsync isn't always respecting the allow/deny tags`.

**Comment by zoredache** [comment] 2023-10-17 18:01
Digging further, this might be an  invalid issue, and there might be some weird corruption in my registry.  Still trying to figure out what is going on.

**Comment by zoredache** [comment] 2023-10-17 20:28
Ok, I have narrowed this down to something I can repeat with a completely clean registry.

My regsync_filtertest.yml

    version: 1
    creds:
      - registry: registry.example.org:5000
        tls: disabled
    defaults:
      ratelimit:
        min: 60
        retry: 30m
      parallel: 2
      interval: 3h
    sync:
      - platform: linux/amd64
        source: k8s.gcr.io/pause
        target: registry.example.org:5000/k8s.gcr.io/pause
        backup: "backup-previous"
        type: repository
        tags:
          allow:
            - '\d.\d+'
            - 'latest'

Configure regctl for our temp registry to be unauthenticated

    $ mkdir -p regctl ; chown 1000:1000 regctl
    $ docker container run -it --rm --net host \
      -v "$(pwd)/regctl:/home/appuser" \
      regclient/regctl:latest registry set --tls=disabled registry.example.org:5000

start a registry with no volumes

    $ docker run -it --rm -p 5000:5000 --name registry_temp registry:2

use regsync server

    $ docker container run -it --rm --net host \
      -v "$(pwd)/regsync_filtertest.yml:/home/appuser/regsync.yml" \
      regclient/regsync:latest -v debug -c /home/appuser/regsync.yml once
    
    DEBU[2023-10-17T20:13:32Z] Configuring parallel settings                 concurrent=2
    ...

And the output showing what the one-time sync did

    $ docker container run -it --rm --net host \
      -v "$(pwd)/regctl:/home/appuser" \
      regclient/regctl:latest  tag ls registry.example.org:5000/k8s.gcr.io/pause

    1.0
    3.1
    3.2
    3.3
    3.5
    3.6
    3.7
    3.8
    3.9
    latest

Now start `regsync server`, wait a few minutes for the initial sync to complete

    $ docker container run -it --rm --net host \
      -v "$(pwd)/regsync_filtertest.yml:/home/appuser/regsync.yml" \
      regclient/regsync:latest -v debug -c /home/appuser/regsync.yml server
    
    DEBU[2023-10-17T20:13:32Z] Configuring parallel settings                 concurrent=2
    ...

And the output showing what the sync the 'server' did

    $ docker container run -it --rm --net host \
      -v "$(pwd)/regctl:/home/appuser" \
      regclient/regctl:latest  tag ls registry.example.org:5000/k8s.gcr.io/pause

    1.0
    3.1
    3.2
    3.3
    3.4.1
    3.5
    3.6
    3.7
    3.8
    3.9
    go
    latest
    sha256-7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097.sig
    sha256-9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d.sig
    test
    test2

**Comment by sudo-bmitch** [comment] 2023-10-18 00:33
Thanks for the detailed report. That's certainly not the desired behavior. I'll have a look at this tomorrow to see why those filters are getting ignored.

**Comment by sudo-bmitch** [comment] 2023-10-18 23:49
I spent some time trying to reproduce this today without luck. My suspicion was that other entries in the sync array are causing corruption. If that's the case, I have a good idea of where to fix it, but my attempts to reproduce that theory haven't worked. I also tried the pause image you are using, again without luck. Is there any chance another tool is copying content to this registry? Or is there anything else in your scenario that might help to reproduce it?

**Comment by zoredache** [comment] 2023-10-19 21:14
> I also tried the pause image you are using

I mostly picked that as an example because it has a relatively small number of tags, the image was really small, and it not on the docker hub, so I wasn't getting hit by the rate limiting.

> Is there any chance another tool is copying content to this registry?

I literally destroyed the registry between each run, it was completely new.

> My suspicion was that other entries in the sync array are causing corruption. 

The above configuration was the entire configuration I had, the only thing I had changed was to obfuscate the registry name a bit.

I have an updated example with a script you can run, and the exact configuration I use, and the full output from a run on a digitalocean bookworm VPS with docker installed via https://get.docker.com/ from about 30 minutes ago.

The script `run.sh`, configuration, and output is here.

- https://gist.github.com/zoredache/ec796a05318d9b7bb0d569f07f0c32af

**Comment by sudo-bmitch** [comment] 2023-10-20 01:05
> I have an updated example with a script you can run, and the exact configuration I use, and the full output from a run on a digitalocean bookworm VPS with docker installed via https://get.docker.com/ from about 30 minutes ago.

Thanks for the example. I've managed to reproduce it  Now I need to sort out how it was different from my own tests. It's also ruling out the parts of the code I originally suspected. I'll dig into it more tomorrow and hopefully have a fix for this soon.

**Closed** 2023-10-20 23:45 UTC
Labels: bug

**Comment by sudo-bmitch** [comment] 2023-10-20 23:50
Found it! I think the reason I didn't find it in my own tests was because I was starting from an empty repo. Thanks so much for the great example to help track that down. The `regclient/regsync:edge` image has been updated with this fix. If you run into any more issues, don't hesitate to reach out.

**Comment by zoredache** [comment] 2023-10-21 23:08
Thanks. The new release seems to fix things for me.
