### ISSUE TITLE
[Question] Clarifications on how the manifest endpoint should behave in the context of manifests of indexes referenced by other indexes

### ISSUE THREAD

**Issue by andaaron** [regclient/regclient#809] opened 2024-08-22 19:10 UTC
This is related to https://github.com/regclient/regclient/issues/808 and https://github.com/project-zot/zot/issues/2624.

The server contains the following index with digest sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c which can be retrieved using the manifests endpoint.
```
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.index.v1+json",
            "digest": "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9",
            "size": 508
        }
    ]
}
```

The other index with digest "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" has been previously deleted by the user using delete on the manifests endpoint (by tag or digest, zot behaves the same at the moment). So "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" is no longer tracked as a manifest. It could still be present as a regular blob as it is referenced by the index sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c. 

If I want to copy sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c, am getting:

```
regctl image copy -v debug andaaron-cs-bld.insieme.local:8080/test-index@sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c ocidir://local_copy:local-tag
DEBU[0000] Loading docker config                         api= blobChunk=0 blobMax=0 helper= hostname=aci-docker-reg.cisco.com mirrors="[]" name=aci-docker-reg.cisco.com pathPrefix= repoAuth=false tls=enabled user=andaaron
DEBU[0000] Loading docker config                         api= blobChunk=0 blobMax=0 helper= hostname="andaaron-cs-bld.insieme.local:8080" mirrors="[]" name="andaaron-cs-bld.insieme.local:8080" pathPrefix= repoAuth=false tls=enabled user=test
DEBU[0000] Loading host config                           api= blobChunk=0 blobMax=0 helper= hostname="localhost:32896" mirrors="[]" name="localhost:32896" pathPrefix= repoAuth=false tls=disabled user=
DEBU[0000] Loading host config                           api= blobChunk=0 blobMax=0 helper= hostname="andaaron-cs-bld.insieme.local:8080" mirrors="[]" name="andaaron-cs-bld.insieme.local:8080" pathPrefix= repoAuth=false tls=enabled user=test
DEBU[0000] Loading host config                           api= blobChunk=0 blobMax=0 helper= hostname=ghcr.io mirrors="[]" name=ghcr.io pathPrefix= repoAuth=false tls=enabled user=
DEBU[0000] regclient initialized                         VCSRef=832109d4e9ef96982c4a4a8614b276b752509e5b VCSTag=v0.5.7
DEBU[0000] Image copy                                    digest-tags=false recursive=false source="andaaron-cs-bld.insieme.local:8080/test-index@sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c" target="ocidir://local_copy:local-tag"
DEBU[0000] http req                                      method=GET url="https://andaaron-cs-bld.insieme.local:8080/v2/test-index/manifests/sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c" withAuth=false
DEBU[0000] Auth request parsed                           challenge="[{basic map[realm:zot]}]"
DEBU[0000] http req                                      method=GET url="https://andaaron-cs-bld.insieme.local:8080/v2/test-index/manifests/sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c" withAuth=true
DEBU[0000] Copy platform                                 digest="sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" platform="<nil>"
DEBU[0000] http req                                      method=GET url="https://andaaron-cs-bld.insieme.local:8080/v2/test-index/manifests/sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" withAuth=true
DEBU[0000] Request failed                                Status="Not Found" URL="https://andaaron-cs-bld.insieme.local:8080/v2/test-index/manifests/sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9"
copy failed, error getting source: failed to get manifest andaaron-cs-bld.insieme.local:8080/test-index@sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9: request failed: not found [http 404]: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"description":"This error is returned when the manifest, identified by name and tag is unknown to the repository.","reference":"sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9"}}]
```

As you can see above, regctl does a call on the manifests endpoint for "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9". But this blob is only present on the server as a blob, because as a manifest it was deleted using the manifests delete API.
I would have expected it to be downloaded using the blobs API instead, even if it is image metadata (same as you would download and read a config blob).

### Question

So let's clarify the expected behavior, because on image copy regctl assumes a reference of type index can always be read using the manifests API, and this is not implemented as such in zot.
While zot assumes the respective reference needs to point to a valid blob accessible through the blobs API, the content may not be accessible using the manifests API if it was previously the target of a delete API call.

How to harmonize these implementations? (we still have some changes we need to do in zot, but the question is where do we want to get).

Do we:
1. Deny the initial call to delete a manifest or index if it is referenced by another index in order to keep consistency (for both tags and digest refences)?
or
2. We allow the initial call to delete to get through and delete the manifest/index making it accessible for the /blobs endpoint, but making it inaccessible to the /manifests endpoint.
or
3. We start differentiating between delete by tag and delete by digest, making delete by tag to keep the underlying blob, and making it available to the manifests endpoint using the digest, while delete by digest removes it entirely. In case of delete by digest, do we want to error if the digest is referenced by another index?

### Version

```text
VCSTag:     v0.5.7
VCSRef:     832109d4e9ef96982c4a4a8614b276b752509e5b
VCSCommit:  832109d4e9ef96982c4a4a8614b276b752509e5b
VCSState:   clean
VCSDate:    2024-02-06T21:25:52Z
Platform:   linux/amd64
GoVer:      go1.21.6
GoCompiler: gc
```

### Environment
Downloaded binary  on Linux x86. Registry is zot.

### Anything else
- https://github.com/regclient/regclient/issues/808
- https://github.com/project-zot/zot/issues/2624

**Comment by sudo-bmitch** [comment] 2024-08-22 20:37
Manifests and blobs are accessed by separate APIs and a manifest does not become a blob when it is deleted. There's nothing in the spec saying a registry should do that, and it would go against my own expectations. There is some code in regclient to support some unusual uses of an index to include blobs, but this is not used when the media type is a well known manifest, and registries have been known to reject an index that includes references to things that are not manifests. In general, everything listed in the index should only be a manifest and anything else is likely to experience compatibility issues.

There are registries that will reject the manifest delete by digest API because it can create dangling references like this. The API already differentiates between deleting a tag and deleting a digest. Deleting the digest both deletes the manifest and all tags that reference that manifest. Deleting a tag just removes that pointer to the digest and whether the underlying content is deleted is up to the garbage collection.

There is also a push to improve support for a "sparse index" where not all listed manifests are on that registry. This is particularly useful for mirrors in an organization that only needs to serve content for a limited number of platforms. Support for that is slowly getting there in regclient. Some places allow the list of platforms to be copied, but other parts treat a missing manifest as a hard failure.

**Comment by sudo-bmitch** [comment] 2024-08-22 20:44
Rereading the question, I think you want to go with option 3. Treat tags as symlinks to a manifest (digest), and a tag delete just deletes the symlink. Whether the underlying digest is later deleted is up to the garbage collection.

**Comment by Sebastian-Maier** [comment] 2024-08-23 08:50
I would expect a behavior similar to option 3: If I delete the last tag of a manifest/index and it is still referenced by another index (via its digest), I would expect the manifest/index to still be available via the regular manifest API (via its digest).

**Comment by Sebastian-Maier** [comment] 2024-08-23 09:08
@sudo-bmitch BTW: There is now a script available with the commands to reproduce the problem (as you originally requested in https://github.com/regclient/regclient/issues/808#issuecomment-2301918686). This script can be found here: https://github.com/project-zot/zot/issues/2624#issuecomment-2306587418

**Comment by sudo-bmitch** [comment] 2024-08-23 14:31
> @sudo-bmitch BTW: There is now a script available with the commands to reproduce the problem (as you originally requested in [#808 (comment)](https://github.com/regclient/regclient/issues/808#issuecomment-2301918686)). This script can be found here: [project-zot/zot#2624 (comment)](https://github.com/project-zot/zot/issues/2624#issuecomment-2306587418)

Thanks. FYI, there are a few bugs I see in the script. The size needs to be the original manifest size, so you'd want to use `--format raw-body` to get the unmodified body of the manifest to calculate that. Upstream tools may or may not format the json with whitespace, and could change the field ordering. Also, while not recommended, it's possible that the media type is not included in the manifest body.

You can get a full descriptor generated by regctl with a command like:

```shell
regctl manifest head --require-digest --format '{{json .GetDescriptor}}' ghcr.io/regclient/regctl:latest
```

And even easier is to have `regctl` create the index with a single command, which includes the needed copy commands:

```shell
regctl index create localhost:5002/demo/index:latest --ref ghcr.io/regclient/regctl:latest
```

**Comment by andaaron** [comment] 2024-08-26 07:24
Double checking to be sure (I think this is more of a dist spec question). On image UPLOAD, is there a guarantee the client would be pushing both the multiarch image index and the manifests using the /manifests endpoint? Or are clients allowed to push the manifests as blobs, and just the index to the /manifests endpoint?

In this specific case is there a dist spec guarantee "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" would be initially pushed to the manifests endpoint before "sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c"? Or the dist spec only guarantees "sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c" is pushed to the manifests endpoint? 
Theoretically "sha256:9bfb6783db1a79ce62781b08afa14edf22912612e486da9ae7a49d68825e4d4c" could still be a valid image if "sha256:79ea4dd4b676f0059664fc75ed196eaee7e4d13de2e97bd6530f4de981586cb9" is present on the server after being pushed as a blob, right?

**Comment by Sebastian-Maier** [comment] 2024-08-26 09:23
> > @sudo-bmitch BTW: There is now a script available with the commands to reproduce the problem (as you originally requested in [#808 (comment)](https://github.com/regclient/regclient/issues/808#issuecomment-2301918686)). This script can be found here: [project-zot/zot#2624 (comment)](https://github.com/project-zot/zot/issues/2624#issuecomment-2306587418)
> 
> Thanks. FYI, there are a few bugs I see in the script. The size needs to be the original manifest size, so you'd want to use `--format raw-body` to get the unmodified body of the manifest to calculate that. Upstream tools may or may not format the json with whitespace, and could change the field ordering. Also, while not recommended, it's possible that the media type is not included in the manifest body.
> 
> You can get a full descriptor generated by regctl with a command like:
> 
> ```shell
> regctl manifest head --require-digest --format '{{json .GetDescriptor}}' ghcr.io/regclient/regctl:latest
> ```
> 
> And even easier is to have `regctl` create the index with a single command, which includes the needed copy commands:
> 
> ```shell
> regctl index create localhost:5002/demo/index:latest --ref ghcr.io/regclient/regctl:latest
> ```

Thank you for all the insights. I fixed the actual bug in the test script for now. Apart from that we will also consider to adjust our PoC tool implementation and replace the manual creation of manifests/indexes with these more powerful commands where appropriate.

**Comment by sudo-bmitch** [comment] 2024-08-26 11:48
> Double checking to be sure (I think this is more of a dist spec question). On image UPLOAD, is there a guarantee the client would be pushing both the multiarch image index and the manifests using the /manifests endpoint? Or are clients allowed to push the manifests as blobs, and just the index to the /manifests endpoint?

I'd personally treat pushing or pulling an entry from the manifests in an index using the blob API as a bug. But there are broken implementations out there (specifically buildkit pushed its cache to registries with an index of blobs, which I think is now fixed). It would be best to follow up with distribution-spec to avoid implementing my personal opinions.

**Comment by andaaron** [comment] 2024-08-26 12:10
Opened https://github.com/opencontainers/distribution-spec/issues/550

**Comment by sudo-bmitch** [comment] 2024-08-26 14:51
Thanks. I'll close this out here and will follow the discussion over in distribution-spec.

**Closed by sudo-bmitch** 2024-08-26 14:51 UTC
Labels: question
