### ISSUE TITLE
[Issue] users shouldn't be required to know which artifacts method is being used

### ISSUE THREAD

**Issue by rchincha** [regclient/regclient#505] opened 2023-07-27 22:42 UTC
### Current Behavior

artifacts can be stored using artifactType or config.mediaType=artifactType methods.

https://github.com/regclient/regclient/blob/main/cmd/regctl/artifact.go#L263

--config-file forces the config.mediaType method, but how would users know which method was used?

### Expected Behavior

Instead, auto-detect and do the right thing. In fact, for either method just use the --output-dir option.

### Version

```text
(paste output of `regctl version` or similar for binaries, or `docker image inspect regclient/...` on the image and paste the labels)
```
```
$ regctl version
VCSTag:     v0.5.0
VCSRef:     c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb-dirty
VCSCommit:  c7e747e56eb507aa7f44e61362a3bd9f8b0b37fb
VCSState:   dirty
VCSDate:    2023-06-28T17:37:27Z
Platform:   linux/amd64
GoVer:      go1.20
GoCompiler: gc
```
### Environment

- Running as binary or container:
- Host platform:
- Registry description:

**Comment by sudo-bmitch** [comment] 2023-07-29 13:26
@rchincha What steps are you running to reproduce this one? The only way I'm thinking of to trigger an error is with the unsupported artifact manifest. For both methods of pushing an image manifest, there is a config blob but one is emtpy, and I'm not sure what "the right thing" is if someone asks for the config content as the manifest has the empty blob.

**Comment by rchincha** [comment] 2023-07-29 16:24
Here is an example manifest that is being pushed from a different client but being pulled using regclient.

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/spdx+json",
    "digest": "sha256:65c6f3619382b9a9e9ffb244f254df9c8bc18bb1ddeee4af4de1435aaff633d2",
    "size": 5236793
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.empty.v1+json",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "size": 2,
      "data": "e30="
    }
  ],
  "subject": {
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "digest": "sha256:6f4e7eb4cc73cea102c83c12dac05c0e529770cc6f11a7f70e53c00936ea224f",
    "size": 2205
  }
}
```

**Comment by sudo-bmitch** [comment] 2023-07-29 16:36
Oh, wow, what client does that? All the guidance I've seen puts the artifact content in the layer, not in the config.

**Comment by rchincha** [comment] 2023-07-29 19:14
Just an experimental homegrown client zot folks were playing with. The idea is that this would still work with a 1.0 dist-spec registry (at least in most cases)

**Comment by sudo-bmitch** [comment] 2023-10-06 20:29
Closing this one out as not planned since artifact content is recommended to always be in the layer blobs.

**Closed by sudo-bmitch** 2023-10-06 20:29 UTC
Labels: bug
