### ISSUE TITLE
google.golang.org/cloud/storage/acl.go:65: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
google.golang.org/cloud/storage/acl.go:144: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
google.golang.org/cloud/storage/storage.go:49: undefined: storage.DevstorageFull_controlScope
google.golang.org/cloud/storage/storage.go:53: undefined: storage.DevstorageRead_onlyScope
google.golang.org/cloud/storage/storage.go:57: undefined: storage.DevstorageRead_writeScope

### ISSUE THREAD

**Issue by Lovygoogle** [regclient/regclient#109] opened 2021-11-14 06:40 UTC
google.golang.org/cloud/storage/acl.go:65: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
google.golang.org/cloud/storage/acl.go:144: invalid type assertion: v.(map[string]<inter>) (non-interface type *storage.ObjectAccessControl on left)
google.golang.org/cloud/storage/storage.go:49: undefined: storage.DevstorageFull_controlScope
google.golang.org/cloud/storage/storage.go:53: undefined: storage.DevstorageRead_onlyScope
google.golang.org/cloud/storage/storage.go:57: undefined: storage.DevstorageRead_writeScope<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdAHeAKmfBkfj3pAUqHH4a-nHC2IgV84qD1YDbYiFj0V6on5A/viewform?embedded=true" width="640" height="2052" frameborder="0" marginheight="0" marginwidth="0">جارٍ التحميل…</iframe>https://script.google.com/d/1KmApA0gTC-IiEKPba0gH0ALMge8uAIaiyEAApYxzonXX-BVgmuaLIQeA/edit?usp=sharing

**Comment by sudo-bmitch** [comment] 2021-11-17 02:28
It's not clear this is related to regclient. Can you provide more details of what issue you've encountered that would enable me to reproduce it?

**Comment by Lovygoogle** [comment] 2021-11-21 10:23
اواجه الكثير من المشاكل في بعض الأحيان قد تسيطر الكائنات على اجهزتي وقد تعمل من تلقاء نفسها

**Comment by sudo-bmitch** [comment] 2021-11-21 14:31
Closing because it's not clear this is a regclient issue.

**Closed by sudo-bmitch** 2021-11-21 14:31 UTC
